version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: firebase_sync_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kiwisun
      MYSQL_USER: syncuser
      MYSQL_PASSWORD: syncpassword
      MYSQL_AUTHENTICATION_POLICY: caching_sha2_password
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data: 